In [2]:
import numpy as np
X = np.array([
    [1.0, 0.0, 1.0],
    [0.0, 2.0, 1.0],
    [1.0, 1.0, 0.0]
])

print("Input Embeddings (X):")
print(X)
e
np.random.seed(45)
d_model = X.shape[1]
d_k = 3

WQ = np.random.random((d_model, d_k))
WK = np.random.random((d_model, d_k))
WV = np.random.random((d_model, d_k))

Q = X @ WQ
K = X @ WK
V = X @ WV
print("\nQuery (Q):")
print(Q)
print("\nKey (K):")
print(K)
print("\nValue (V):")
print(V)

scores = Q @ K.T
print("\nAttention Scores:")
print(scores)

scaled_scores = scores / np.sqrt(d_k)
print("\nScaled Scores:")
print(scaled_scores)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scaled_scores)
print("\nAttention Weights:")
print(attention_weights)

attention_output = attention_weights @ V
print("\nFinal Attention Output:")
print(attention_output)

Input Embeddings (X):
[[1. 0. 1.]
 [0. 2. 1.]
 [1. 1. 0.]]

Query (Q):
[[1.03753351 0.71286918 0.39739801]
 [0.20310113 1.05226344 1.06156665]
 [1.06630108 0.99401422 0.75425527]]

Key (K):
[[0.91005889 1.83218536 1.32317042]
 [2.26411058 1.91670481 1.90965697]
 [1.61811337 1.3265328  1.2683969 ]]

Value (V):
[[0.68328905 0.67766986 1.32857311]
 [0.46767995 0.8418921  1.77597804]
 [0.55299178 0.51664213 0.98825199]]

Attention Scores:
[[2.77615036 4.47434427 3.1285496 ]
 [3.51740926 4.50394997 3.07099048]
 [3.78962335 5.75982423 4.00068355]]

Scaled Scores:
[[1.60281116 2.58326387 1.80626895]
 [2.03077718 2.60035673 1.77303718]
 [2.18794006 3.32543607 2.30979572]]

Attention Weights:
[[0.20444479 0.54498085 0.25057436]
 [0.28246035 0.49925538 0.21828427]
 [0.19052918 0.59425076 0.21522006]]

Final Attention Output:
[[0.53313706 0.72681841 1.48712448]
 [0.5472032  0.72450887 1.47765568]
 [0.52712059 0.74060265 1.5211999 ]]
